### PR TITLE
Reach for the arcs

### PR DESCRIPTION
**Pull request by odedstein**
This pull request adds the code to perform reach_for_the_arcs to Gpytoolbox.

@sgsellan please check whether this is ok, and whether we should tweak any RFTA default parameters.
Also please take a look at whether you like the unit tests.

This pull request depends on #117 , and should only be merged after that one has been merged.

### CODE REVIEW

**Comment by odedstein** [comment]
The built currently fails on Windows.
I currently don't have access to a Windows to debug this.

**Comment by sgsellan** [comment]
The previous tests seemed to be timing out in an install, so I am trying out removing it...

**Comment by odedstein** [comment]
The Linux wheels seem to build correctly now after the latest change.

**Comment by odedstein** [comment]
If the merge commit clears all tests, this can be merged.

**Comment by sgsellan** [comment]
Added an extra check to the RFTS singularity catching, now that we don't consistently get NaNs in the vertex values (because of our fix of #119 ). A liiiitle uneasy that the tests only failed in some OS, but it should be fixed now. I am happy to merge if this looks reasonable to you and checks pass

**Review by sgsellan — APPROVED** [review]

**Pull request merged**
