### PR TITLE
Add a warning in remesch_botsch if all vertices are detected as boundary vertices

### PR DESCRIPTION
**Pull request by EmJay276**
If all vertices of a mesh are detected as boundary vertices, the remesh_botsch will return the input.
I've added a warning to make the user aware in this case (L65 - L67).

Additionally, I applied PEP8 style guide (whitespace) to the code.

### CODE REVIEW

**Comment by EmJay276** [comment]
Minimal example for https://github.com/sgsellan/gpytoolbox/pull/69#issuecomment-1446234477

```
import gpytoolbox as gpy
import numpy as np

v = np.array(((0., 0., 0.),
              (10, 0., 0.),
              (0., 10, 0.),
              (10, 10, 0.)))

f = np.array(((0, 1, 3),
              (0, 2, 3)), dtype=np.int32)

u, g = gpy.remesh_botsch(v, f, h=1.)

print(f"Input: {v.shape = }, {f.shape = }")
print(f"Output: {u.shape = }, {g.shape = }")
```

Result
```
Input: v.shape = (4, 3), f.shape = (2, 3)
Output: u.shape = (4, 3), g.shape = (2, 3)
```

I would at least suggest to warn the user.
As user I would also expect the remesher should add vertices within the plane / at the edges.

**Comment by sgsellan** [comment]
This makes sense! Still, in L66, shouldn't we compare the length of `V` to the length of _the unique entries of `feature`_? Since `feature` is concatenating the user input and boundary vertices, its length could actually be larger than the size of `V` if, for example, I ran `u, g = gpy.remesh_botsch(v, f, h=1.,feature=np.array([0],dtype=np.int32))` on your example above, which would not currently trigger the warning. Speaking off the cuff, free to tell me if I'm wrong!

**Comment by EmJay276** [comment]
Indeed! Fixed with https://github.com/sgsellan/gpytoolbox/pull/69/commits/7bdcd09a5d2db72f6c87641d79661ebe7a2dc14c

**Comment by sgsellan** [comment]
Awesome! I'll merge after checks.

Also, what is this PEP8 style guide? Should we apply it across the whole library?

**Comment by EmJay276** [comment]
> Also, what is this PEP8 style guide? Should we apply it across the whole library?

It's the Python Enhancement Proposals (PEP) for "Style Guide for Python Code"
https://peps.python.org/pep-0008/

PEP8 is mainly code formatting, which most Python IDEs automatically suggest. Including my IDE (PyCharm).

I'm my opinion it makes the code easier to read.

For example `u = (0, 1 * 2)` instead of `u=(0,1*2)`

**Pull request merged**
