### PR TITLE
Clean up sdf_flow

### PR DESCRIPTION
**Pull request by odedstein**
Clean up sdf_flow to make it library-ready.
The function still has TODOs that need to be addressed.

### CODE REVIEW

**Comment by odedstein** [comment]
It remains to write a docstring for this functions, working on that next.

**Comment by sgsellan** [comment]
Also: rename the function to `reach_for_the_spheres`

**Comment by sgsellan** [comment]
Let me know when this is ready!

**Review by sgsellan — APPROVED** [review]
Seems good to me! Ready to merge

**Pull request merged**
